<?php

// ============================================
// 4. database/seeders/ClassSeeder.php
// ============================================

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GymClass;
use Illuminate\Support\Str;

class ClassSeeder extends Seeder
{
    public function run(): void
    {
        $classes = [
            // Yoga Classes
            [
                'name' => 'Morning Yoga Flow',
                'description' => 'Bắt đầu ngày mới với năng lượng tích cực. Lớp Yoga buổi sáng giúp bạn thư giãn, tăng cường sự linh hoạt và cải thiện tư thế.',
                'benefits' => 'Giảm stress, tăng sự linh hoạt, cải thiện tư thế, tăng cường sức khỏe tinh thần.',
                'trainer_id' => 1,
                'level' => 'beginner',
                'category' => 'yoga',
                'duration' => 60,
                'start_time' => '06:00',
                'days_of_week' => ['monday', 'wednesday', 'friday'],
                'start_date' => now(),
                'end_date' => now()->addMonths(3),
                'max_participants' => 15,
                'min_participants' => 5,
                'price' => 200000,
                'package_price' => 1800000,
                'is_free_trial' => true,
                'room' => 'Phòng Yoga 1',
                'requirements' => 'Mang thảm yoga, khăn và nước uống',
                'calories_burn' => 150,
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'total_reviews' => 24,
            ],
            [
                'name' => 'Power Yoga',
                'description' => 'Yoga cường độ cao kết hợp với bài tập sức mạnh. Phù hợp cho người đã có kinh nghiệm và muốn thử thách bản thân.',
                'benefits' => 'Tăng cường sức mạnh cơ bắp, cải thiện sức bền, đốt cháy calo hiệu quả.',
                'trainer_id' => 1,
                'level' => 'advanced',
                'category' => 'yoga',
                'duration' => 75,
                'start_time' => '18:00',
                'days_of_week' => ['tuesday', 'thursday'],
                'max_participants' => 12,
                'min_participants' => 5,
                'price' => 250000,
                'package_price' => 2200000,
                'room' => 'Phòng Yoga 1',
                'calories_burn' => 350,
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'total_reviews' => 18,
            ],

            // Strength Training
            [
                'name' => 'Strength Foundation',
                'description' => 'Lớp học cơ bản về tập tạ và xây dựng sức mạnh. Phù hợp cho người mới bắt đầu muốn học kỹ thuật đúng.',
                'benefits' => 'Xây dựng nền tảng sức mạnh, học kỹ thuật tập luyện đúng, tăng khối lượng cơ bắp.',
                'trainer_id' => 2,
                'level' => 'beginner',
                'category' => 'strength',
                'duration' => 60,
                'start_time' => '14:00',
                'days_of_week' => ['monday', 'thursday'],
                'max_participants' => 10,
                'min_participants' => 4,
                'price' => 300000,
                'package_price' => 2700000,
                'room' => 'Phòng tập tạ 1',
                'requirements' => 'Giày thể thao, khăn, nước',
                'calories_burn' => 400,
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.9,
                'total_reviews' => 35,
            ],
            [
                'name' => 'Bodybuilding Pro',
                'description' => 'Chương trình tập luyện chuyên sâu cho người muốn tăng cơ bắp. Bao gồm kỹ thuật nâng cao và hướng dẫn dinh dưỡng.',
                'benefits' => 'Tăng khối cơ tối đa, giảm mỡ, định hình cơ thể ấn tượng.',
                'trainer_id' => 2,
                'level' => 'advanced',
                'category' => 'strength',
                'duration' => 90,
                'start_time' => '19:00',
                'days_of_week' => ['tuesday', 'thursday', 'saturday'],
                'max_participants' => 8,
                'min_participants' => 3,
                'price' => 400000,
                'package_price' => 3600000,
                'room' => 'Phòng tập tạ 2',
                'calories_burn' => 500,
                'status' => 'active',
                'rating' => 4.9,
                'total_reviews' => 28,
            ],

            // Cardio & Dance
            [
                'name' => 'Zumba Party',
                'description' => 'Nhảy múa và tập luyện cùng lúc! Zumba kết hợp nhạc Latin sôi động với các động tác aerobic dễ học.',
                'benefits' => 'Đốt cháy calo, cải thiện nhịp tim, giảm stress, vui vẻ và tăng tự tin.',
                'trainer_id' => 3,
                'level' => 'beginner',
                'category' => 'dance',
                'duration' => 60,
                'start_time' => '18:00',
                'days_of_week' => ['tuesday', 'thursday', 'saturday'],
                'max_participants' => 25,
                'min_participants' => 8,
                'price' => 180000,
                'package_price' => 1600000,
                'is_free_trial' => true,
                'room' => 'Phòng Dance',
                'calories_burn' => 600,
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'total_reviews' => 42,
            ],
            [
                'name' => 'HIIT Burn',
                'description' => 'High Intensity Interval Training - Tập luyện ngắn nhưng cực kỳ hiệu quả. Đốt cháy mỡ thừa chỉ trong 45 phút.',
                'benefits' => 'Đốt cháy calo cực cao, tăng tốc độ trao đổi chất, cải thiện sức bền tim mạch.',
                'trainer_id' => 3,
                'level' => 'intermediate',
                'category' => 'cardio',
                'duration' => 45,
                'start_time' => '19:30',
                'days_of_week' => ['monday', 'wednesday', 'friday'],
                'max_participants' => 20,
                'min_participants' => 6,
                'price' => 220000,
                'package_price' => 2000000,
                'room' => 'Phòng Cardio',
                'calories_burn' => 700,
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'total_reviews' => 31,
            ],

            // Boxing
            [
                'name' => 'Boxing Basics',
                'description' => 'Học các kỹ thuật Boxing cơ bản từ cựu võ sĩ chuyên nghiệp. An toàn, hiệu quả và phù hợp cho mọi người.',
                'benefits' => 'Tự vệ, tăng sự tự tin, giải tóa stress, tăng cường phản xạ.',
                'trainer_id' => 4,
                'level' => 'beginner',
                'category' => 'boxing',
                'duration' => 60,
                'start_time' => '18:00',
                'days_of_week' => ['monday', 'wednesday', 'friday'],
                'max_participants' => 15,
                'min_participants' => 5,
                'price' => 280000,
                'package_price' => 2500000,
                'room' => 'Phòng Boxing',
                'requirements' => 'Băng tay, găng boxing (có cho thuê)',
                'calories_burn' => 600,
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.9,
                'total_reviews' => 45,
            ],
            [
                'name' => 'Kickboxing Advanced',
                'description' => 'Lớp Kickboxing nâng cao với kỹ thuật đá và đấm chuyên nghiệp. Tập luyện cường độ cao.',
                'benefits' => 'Kỹ năng tự vệ chuyên nghiệp, sức mạnh toàn thân, sự linh hoạt tuyệt vời.',
                'trainer_id' => 4,
                'level' => 'advanced',
                'category' => 'boxing',
                'duration' => 75,
                'start_time' => '20:00',
                'days_of_week' => ['tuesday', 'thursday', 'saturday'],
                'max_participants' => 12,
                'min_participants' => 4,
                'price' => 350000,
                'package_price' => 3200000,
                'room' => 'Phòng Boxing',
                'calories_burn' => 750,
                'status' => 'active',
                'rating' => 4.8,
                'total_reviews' => 22,
            ],

            // CrossFit
            [
                'name' => 'CrossFit Fundamentals',
                'description' => 'Giới thiệu về CrossFit và functional training. Học các động tác cơ bản an toàn và hiệu quả.',
                'benefits' => 'Sức mạnh tổng thể, sức bền, tính linh hoạt, khả năng vận động chức năng.',
                'trainer_id' => 5,
                'level' => 'beginner',
                'category' => 'crossfit',
                'duration' => 60,
                'start_time' => '06:00',
                'days_of_week' => ['monday', 'wednesday', 'friday'],
                'max_participants' => 15,
                'min_participants' => 5,
                'price' => 300000,
                'package_price' => 2700000,
                'room' => 'Phòng CrossFit',
                'requirements' => 'Giày training, khăn, nước',
                'calories_burn' => 550,
                'status' => 'active',
                'rating' => 4.7,
                'total_reviews' => 19,
            ],
            [
                'name' => 'WOD - Workout of the Day',
                'description' => 'Workout thay đổi mỗi ngày với cường độ cao. Thử thách giới hạn của bản thân trong môi trường cộng đồng.',
                'benefits' => 'Phát triển toàn diện, cộng đồng hỗ trợ, luôn mới mẻ và thử thách.',
                'trainer_id' => 5,
                'level' => 'intermediate',
                'category' => 'crossfit',
                'duration' => 60,
                'start_time' => '18:00',
                'days_of_week' => ['tuesday', 'thursday', 'saturday'],
                'max_participants' => 12,
                'min_participants' => 4,
                'price' => 320000,
                'package_price' => 2900000,
                'room' => 'Phòng CrossFit',
                'calories_burn' => 600,
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.6,
                'total_reviews' => 15,
            ],
        ];

        foreach ($classes as $classData) {
            $classData['slug'] = Str::slug($classData['name']);
            GymClass::create($classData);
        }

        $this->command->info('Created ' . count($classes) . ' classes');
    }
}
